name: ci

on:
  pull_request:
  merge_group:

jobs:
  clippy:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: Run clippy
        run: cargo clippy
  
  test:
    needs:
      - clippy
    strategy:
      matrix:
        os:
          - ubuntu-latest
        rust-toolchain:
          - "stable"
          - "nightly"
          - "1.56.1"
        release-flag:
          - "--release"
          - ""
        passthrough-flag:
          - "--features=passthrough"
          - ""
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust-toolchain }}
      - name: Run tests
        run: cargo test ${{ matrix.release-flag }} ${{ matrix.passthrough-flag }}
